package com.epms.backend.audit;

public final class AuditActionType {
	private AuditActionType() {
	}

	public static final String EMPLOYEE_ACCOUNT_CREATED = "EMPLOYEE_ACCOUNT_CREATED";
	public static final String TEMP_PASSWORD_RESENT = "TEMP_PASSWORD_RESENT";
	public static final String PASSWORD_CHANGED_FIRST_LOGIN = "PASSWORD_CHANGED_FIRST_LOGIN";
	public static final String EMPLOYEE_INFO_UPDATED = "EDIT_EMPLOYEE_INFO";
	public static final String NEW_TEMP_PASSWORD_SENT = "SEND_NEW_TEMP_PASSWORD";
	public static final String EMPLOYMENT_STATUS_UPDATED = "EMPLOYMENT_STATUS_UPDATED";
	public static final String FORGOT_PASSWORD_OTP_SENT = "FORGOT_PASSWORD_OTP_SENT";
	public static final String FORGOT_PASSWORD_OTP_RESENT = "FORGOT_PASSWORD_OTP_RESENT";
	public static final String FORGOT_PASSWORD_OTP_VERIFIED = "FORGOT_PASSWORD_OTP_VERIFIED";
	public static final String FORGOT_PASSWORD_RESET_SUCCESS = "FORGOT_PASSWORD_RESET_SUCCESS";
	public static final String FORGOT_PASSWORD_RESET_FAILED = "FORGOT_PASSWORD_RESET_FAILED";
	public static final String EMPLOYEE_BULK_IMPORT = "EMPLOYEE_BULK_IMPORT";
	public static final String TIME_SETTINGS_UPDATED = "TIME_SETTINGS_UPDATED";

	public static final String EMPLOYEE_TEMPORARY_TRANSFER = "EMPLOYEE_TEMPORARY_TRANSFER";
	public static final String EMPLOYEE_PERMANENT_TRANSFER = "EMPLOYEE_PERMANENT_TRANSFER";
	public static final String EMPLOYEE_RETURN = "EMPLOYEE_RETURN";
	public static final String EMPLOYEE_INITIAL_TRANSFER = "EMPLOYEE_INITIAL_TRANSFER";
	public static final String SNAPSHOT_CREATED = "SNAPSHOT_CREATED";
	public static final String MANAGER_ASSIGNED = "MANAGER_ASSIGNED";

	public static final String SELF_ASSESSMENT_FORM_DRAFT_SAVED = "SELF_ASSESSMENT_FORM_DRAFT_SAVED";
	public static final String SELF_ASSESSMENT_FORM_SUBMITTED = "SELF_ASSESSMENT_FORM_SUBMITTED";
	public static final String SELF_ASSESSMENT_FORM_MANAGER_REVIEWED = "SELF_ASSESSMENT_FORM_MANAGER_REVIEWED";
	public static final String SELF_ASSESSMENT_FORM_MANAGER_FORCE_CHANGED_RETAKE = "SELF_ASSESSMENT_FORM_MANAGER_FORCE_CHANGED_RETAKE";
	public static final String SELF_ASSESSMENT_FORM_MANAGER_ADJUSTMENT_PROPOSED = "SELF_ASSESSMENT_FORM_MANAGER_ADJUSTMENT_PROPOSED";
	public static final String SELF_ASSESSMENT_FORM_HR_APPROVED_ADJUSTMENT = "SELF_ASSESSMENT_FORM_HR_APPROVED_ADJUSTMENT";
	public static final String SELF_ASSESSMENT_FORM_HR_REJECTED_ADJUSTMENT = "SELF_ASSESSMENT_FORM_HR_REJECTED_ADJUSTMENT";
	public static final String SELF_ASSESSMENT_FORM_HR_SENT_BACK_TO_MANAGER = "SELF_ASSESSMENT_FORM_HR_SENT_BACK_TO_MANAGER";
	public static final String SELF_ASSESSMENT_FORM_HR_APPROVED = "SELF_ASSESSMENT_FORM_HR_APPROVED";
	public static final String SELF_ASSESSMENT_FORM_HR_REOPENED = "SELF_ASSESSMENT_FORM_HR_REOPENED";
	public static final String SELF_ASSESSMENT_FORM_HR_UNLOCKED_RETAKE = "SELF_ASSESSMENT_FORM_HR_UNLOCKED_RETAKE";
	public static final String SELF_ASSESSMENT_FORM_UNLOCK_REQUESTED = "SELF_ASSESSMENT_FORM_UNLOCK_REQUESTED";
	public static final String SELF_ASSESSMENT_FORM_UNLOCKED = "SELF_ASSESSMENT_FORM_UNLOCKED";
	public static final String SELF_ASSESSMENT_FORM_UNLOCK_REJECTED = "SELF_ASSESSMENT_FORM_UNLOCK_REJECTED";
	public static final String SELF_ASSESSMENT_FORM_RESUBMITTED_AFTER_UNLOCK = "SELF_ASSESSMENT_FORM_RESUBMITTED_AFTER_UNLOCK";
	public static final String SELF_ASSESSMENT_FORM_TEMPLATE_CREATED = "SELF_ASSESSMENT_FORM_TEMPLATE_CREATED";
	public static final String SELF_ASSESSMENT_FORM_TEMPLATE_UPDATED = "SELF_ASSESSMENT_FORM_TEMPLATE_UPDATED";
	public static final String QUESTION_BANK_CREATED = "QUESTION_BANK_CREATED";
	public static final String QUESTION_BANK_UPDATED = "QUESTION_BANK_UPDATED";
	public static final String QUESTION_BANK_STATUS_CHANGED = "QUESTION_BANK_STATUS_CHANGED";

	public static final String FEEDBACK_360_SUBMITTED = "FEEDBACK_360_SUBMITTED";
	public static final String SCORE_EXPLANATION_UPDATED = "SCORE_EXPLANATION_UPDATED";
	
	public static final String KPI_CREATED = "KPI_CREATED";
	public static final String KPI_UPDATED = "KPI_UPDATED";
	public static final String KPI_DRAFT_SAVED = "KPI_DRAFT_SAVED";
	public static final String KPI_SUBMITTED = "KPI_SUBMITTED";
	public static final String KPI_MONTHLY_RESET = "KPI_MONTHLY_RESET";
	
	public static final String EMPLOYEE_PROMOTION = "EMPLOYEE_PROMOTION";

	public static final String PERMISSION_MATRIX_UPDATED = "PERMISSION_MATRIX_UPDATED";
	public static final String EMPLOYEE_PERMISSION_UPDATED = "EMPLOYEE_PERMISSION_UPDATED";

	public static final String CONTINUOUS_FEEDBACK_CREATED = "CONTINUOUS_FEEDBACK_CREATED";
	public static final String CONTINUOUS_FEEDBACK_PRIVATE_NOTE_UPDATED = "CONTINUOUS_FEEDBACK_PRIVATE_NOTE_UPDATED";
	public static final String CONTINUOUS_FEEDBACK_SHARED = "CONTINUOUS_FEEDBACK_SHARED";
	public static final String CONTINUOUS_FEEDBACK_ACKNOWLEDGED = "CONTINUOUS_FEEDBACK_ACKNOWLEDGED";
	public static final String CONTINUOUS_FEEDBACK_COMMENT_ADDED = "CONTINUOUS_FEEDBACK_COMMENT_ADDED";
	public static final String CONTINUOUS_FEEDBACK_ACTION_ITEM_CREATED = "CONTINUOUS_FEEDBACK_ACTION_ITEM_CREATED";
	public static final String CONTINUOUS_FEEDBACK_ACTION_ITEM_STATUS_UPDATED = "CONTINUOUS_FEEDBACK_ACTION_ITEM_STATUS_UPDATED";
	public static final String CONTINUOUS_FEEDBACK_PIP_WARNING_TRIGGERED = "CONTINUOUS_FEEDBACK_PIP_WARNING_TRIGGERED";
	public static final String CONTINUOUS_FEEDBACK_PIP_CREATED = "CONTINUOUS_FEEDBACK_PIP_CREATED";
	public static final String CONTINUOUS_FEEDBACK_MEETING_CREATED = "CONTINUOUS_FEEDBACK_MEETING_CREATED";
}
