package com.epms.backend.audit;

public final class AuditActionType {
	private AuditActionType() {
	}

	public static final String EMPLOYEE_ACCOUNT_CREATED = "EMPLOYEE_ACCOUNT_CREATED";
	public static final String TEMP_PASSWORD_RESENT = "TEMP_PASSWORD_RESENT";
	public static final String PASSWORD_CHANGED_FIRST_LOGIN = "PASSWORD_CHANGED_FIRST_LOGIN";
	public static final String EMPLOYEE_INFO_UPDATED = "EDIT_EMPLOYEE_INFO";
	public static final String NEW_TEMP_PASSWORD_SENT = "SEND_NEW_TEMP_PASSWORD";
	public static final String EMPLOYMENT_STATUS_UPDATED = "EMPLOYMENT_STATUS_UPDATED";
	public static final String FORGOT_PASSWORD_OTP_SENT = "FORGOT_PASSWORD_OTP_SENT";
	public static final String FORGOT_PASSWORD_OTP_RESENT = "FORGOT_PASSWORD_OTP_RESENT";
	public static final String FORGOT_PASSWORD_OTP_VERIFIED = "FORGOT_PASSWORD_OTP_VERIFIED";
	public static final String FORGOT_PASSWORD_RESET_SUCCESS = "FORGOT_PASSWORD_RESET_SUCCESS";
	public static final String FORGOT_PASSWORD_RESET_FAILED = "FORGOT_PASSWORD_RESET_FAILED";
	public static final String EMPLOYEE_BULK_IMPORT = "EMPLOYEE_BULK_IMPORT";

	public static final String EMPLOYEE_TEMPORARY_TRANSFER = "EMPLOYEE_TEMPORARY_TRANSFER";
	public static final String EMPLOYEE_PERMANENT_TRANSFER = "EMPLOYEE_PERMANENT_TRANSFER";
	public static final String EMPLOYEE_RETURN = "EMPLOYEE_RETURN";
	public static final String EMPLOYEE_INITIAL_TRANSFER = "EMPLOYEE_INITIAL_TRANSFER";
	public static final String SNAPSHOT_CREATED = "SNAPSHOT_CREATED";

	public static final String SELF_ASSESSMENT_FORM_DRAFT_SAVED = "SELF_ASSESSMENT_FORM_DRAFT_SAVED";
	public static final String SELF_ASSESSMENT_FORM_SUBMITTED = "SELF_ASSESSMENT_FORM_SUBMITTED";
	public static final String SELF_ASSESSMENT_FORM_MANAGER_REVIEWED = "SELF_ASSESSMENT_FORM_MANAGER_REVIEWED";
	public static final String SELF_ASSESSMENT_FORM_MANAGER_ADJUSTMENT_PROPOSED = "SELF_ASSESSMENT_FORM_MANAGER_ADJUSTMENT_PROPOSED";
	public static final String SELF_ASSESSMENT_FORM_HR_APPROVED_ADJUSTMENT = "SELF_ASSESSMENT_FORM_HR_APPROVED_ADJUSTMENT";
	public static final String SELF_ASSESSMENT_FORM_HR_REJECTED_ADJUSTMENT = "SELF_ASSESSMENT_FORM_HR_REJECTED_ADJUSTMENT";
	public static final String SELF_ASSESSMENT_FORM_HR_APPROVED = "SELF_ASSESSMENT_FORM_HR_APPROVED";
	public static final String SELF_ASSESSMENT_FORM_HR_REOPENED = "SELF_ASSESSMENT_FORM_HR_REOPENED";
	public static final String SELF_ASSESSMENT_FORM_TEMPLATE_CREATED = "SELF_ASSESSMENT_FORM_TEMPLATE_CREATED";
	public static final String SELF_ASSESSMENT_FORM_TEMPLATE_UPDATED = "SELF_ASSESSMENT_FORM_TEMPLATE_UPDATED";
}
