export function getDashPageTitle(pathname: string): string {
  if (pathname.includes('/profile')) return 'User Profile'
  if (pathname.includes('/settings/system/time')) return 'Time Settings'
  if (pathname.includes('/settings/system/score-explanations')) return 'Score Explanation'
  if (pathname.includes('/settings')) return 'System Settings'
  if (pathname.includes('/employees/create-account')) return 'Create Employee Account'
  if (pathname.includes('/employees')) return 'Employees'
  if (pathname.includes('/departments')) return 'Departments'
  if (pathname.includes('/positions')) return 'Positions'
  if (pathname.includes('/level-codes')) return 'Level Codes'
  if (pathname.includes('/kpi')) return 'KPI'
  if (pathname.includes('/appraisals')) return 'Appraisals'
  if (pathname.includes('/360-feedback')) return '360° Feedback'
  if (pathname.includes('/pip')) return 'PIP'
  if (pathname.includes('/self-assessment')) return 'Self-Assessment'
  if (pathname.includes('/meetings')) return 'Meetings'
  if (pathname.includes('/reports')) return 'Reports'
  if (pathname.includes('/continuous-feedback/create')) return 'Create Feedback'
  if (pathname.includes('/continuous-feedback')) return 'Continuous Feedback'
  return 'Dashboard'
}
