package com.epms.backend.entity;

public enum SelfAssessmentFormStatus {
    DRAFT,
    SUBMITTED,
    MANAGER_REVIEWED,
    APPROVED,
    NOT_STARTED,
    NOT_SUBMITTED,
    REOPENED,
    PENDING_MANAGER_REVIEW,
    PENDING_EMPLOYEE_REVIEW,
    PENDING_EMPLOYEE_RETAKE,
    PENDING_RETAKE_MANAGER_REVIEW,
    PENDING_FINAL_APPROVAL,
    PENDING_HR_CALIBRATION_REVIEW,
    RETURNED_BY_HR,
    FINALIZED_LOCKED
}
