-- Optional reference: `users` table is created by JPA (`ddl-auto=update`) on startup.
-- Prefer the built-in `AdminDataInitializer` which inserts the admin user with a BCrypt hash.
--
-- If you must seed manually, generate a BCrypt hash for your password and insert:
--   employee_id: 1
--   email: admin@gmail.com
--   role: ADMIN
--   enabled: 1
--
-- Example (password hash is illustrative only — use BCryptPasswordEncoder in Java for real values):
-- INSERT INTO users (employee_id, email, password, role, enabled)
-- VALUES ('1', 'admin@gmail.com', '$2a$10$REPLACE_WITH_BCRYPT_HASH', 'ADMIN', true);
